fix: add the missing indexer VMByNetworkIndex back
fix the compile error since the indexeres.VMByNetworkIndex is
deprecated since harvester 1.4.0

pkg/utils/vmi.go:23:34: undefined: indexeres.VMByNetworkIndex
pkg/utils/vmi.go:27:47: undefined: indexeres.VMByNetworkIndex
pkg/utils/vmi.go:32:50: undefined: indexeres.VMByNetworkIndex
FATA[0126] exit status 1
make: *** [Makefile:11: ci] Error 1

Signed-off-by: Chris Chiu <chris.chiu@suse.com>